// <auto-generated />
using System;
using HydrusComicCompanion.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace HydrusComicCompanion.Data.Migrations
{
    [DbContext(typeof(SettingsDbContext))]
    [Migration("20260627183937_AddAlternateComicPageVariants")]
    partial class AddAlternateComicPageVariants
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.9");

            modelBuilder.Entity("HydrusComicCompanion.Data.ChapterRecord", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<decimal?>("ChapterNumber")
                        .HasColumnType("TEXT");

                    b.Property<int>("SeriesId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Title")
                        .HasColumnType("TEXT");

                    b.Property<int?>("VolumeNumber")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("SeriesId");

                    b.ToTable("Chapters", (string)null);
                });

            modelBuilder.Entity("HydrusComicCompanion.Data.ComicsRecord", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Comment")
                        .HasColumnType("TEXT");

                    b.Property<string>("CoverFileHash")
                        .HasColumnType("TEXT");

                    b.Property<string>("DisplayTitle")
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset?>("LastSyncedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Series", (string)null);
                });

            modelBuilder.Entity("HydrusComicCompanion.Data.HydrusSettingsRecord", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("AlternatePageDefaultValue")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("AlternatePageNamespace")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("ApiUrl")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("BackgroundSyncIntervalMinutes")
                        .HasColumnType("INTEGER");

                    b.Property<string>("ChapterNamespace")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("ComicCommentNoteName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("CoverPageTag")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("FullTitleNoteName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("OcrTextNoteName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("PageNamespace")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("PrimaryTagService")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("ProtectedApiAccessKey")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("TagServiceKey")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("TargetFileDomain")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("TitleNamespace")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("VolumeNamespace")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("HydrusSettings", (string)null);
                });

            modelBuilder.Entity("HydrusComicCompanion.Data.MetadataRecord", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Key")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("SeriesId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Value")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("SeriesId");

                    b.ToTable("Metadata", (string)null);
                });

            modelBuilder.Entity("HydrusComicCompanion.Data.PageRecord", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("ChapterId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("PageNumber")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("ChapterId");

                    b.HasIndex("ChapterId", "PageNumber")
                        .IsUnique();

                    b.ToTable("Pages", (string)null);
                });

            modelBuilder.Entity("HydrusComicCompanion.Data.PageVariantRecord", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("FileHash")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsDefault")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Label")
                        .HasColumnType("TEXT");

                    b.Property<string>("MimeType")
                        .HasColumnType("TEXT");

                    b.Property<string>("OcrText")
                        .HasColumnType("TEXT");

                    b.Property<int>("PageId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("PageId");

                    b.HasIndex("PageId", "FileHash")
                        .IsUnique();

                    b.ToTable("PageVariants", (string)null);
                });

            modelBuilder.Entity("HydrusComicCompanion.Data.ChapterRecord", b =>
                {
                    b.HasOne("HydrusComicCompanion.Data.ComicsRecord", "Comics")
                        .WithMany("Chapters")
                        .HasForeignKey("SeriesId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Comics");
                });

            modelBuilder.Entity("HydrusComicCompanion.Data.MetadataRecord", b =>
                {
                    b.HasOne("HydrusComicCompanion.Data.ComicsRecord", "Comics")
                        .WithMany("Metadata")
                        .HasForeignKey("SeriesId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Comics");
                });

            modelBuilder.Entity("HydrusComicCompanion.Data.PageRecord", b =>
                {
                    b.HasOne("HydrusComicCompanion.Data.ChapterRecord", "Chapter")
                        .WithMany("Pages")
                        .HasForeignKey("ChapterId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Chapter");
                });

            modelBuilder.Entity("HydrusComicCompanion.Data.PageVariantRecord", b =>
                {
                    b.HasOne("HydrusComicCompanion.Data.PageRecord", "Page")
                        .WithMany("Variants")
                        .HasForeignKey("PageId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Page");
                });

            modelBuilder.Entity("HydrusComicCompanion.Data.ChapterRecord", b =>
                {
                    b.Navigation("Pages");
                });

            modelBuilder.Entity("HydrusComicCompanion.Data.ComicsRecord", b =>
                {
                    b.Navigation("Chapters");

                    b.Navigation("Metadata");
                });

            modelBuilder.Entity("HydrusComicCompanion.Data.PageRecord", b =>
                {
                    b.Navigation("Variants");
                });
#pragma warning restore 612, 618
        }
    }
}
