// <auto-generated />
using System;
using HydrusComicCompanion.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace HydrusComicCompanion.Data.Migrations
{
    [DbContext(typeof(SettingsDbContext))]
    [Migration("20260624055631_AddCoverPageTagSetting")]
    partial class AddCoverPageTagSetting
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.9");

            modelBuilder.Entity("HydrusComicCompanion.Data.ChapterRecord", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<decimal?>("ChapterNumber")
                        .HasColumnType("TEXT");

                    b.Property<int>("SeriesId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Title")
                        .HasColumnType("TEXT");

                    b.Property<int?>("VolumeNumber")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("SeriesId");

                    b.ToTable("Chapters", (string)null);
                });

            modelBuilder.Entity("HydrusComicCompanion.Data.HydrusSettingsRecord", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("ApiUrl")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("BackgroundSyncIntervalMinutes")
                        .HasColumnType("INTEGER");

                    b.Property<string>("ChapterNamespace")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("CoverPageTag")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("PageNamespace")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("PrimaryTagService")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("ProtectedApiAccessKey")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("TagServiceKey")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("TargetFileDomain")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("TitleNamespace")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("VolumeNamespace")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("HydrusSettings", (string)null);
                });

            modelBuilder.Entity("HydrusComicCompanion.Data.MetadataRecord", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Key")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("SeriesId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Value")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("SeriesId");

                    b.ToTable("Metadata", (string)null);
                });

            modelBuilder.Entity("HydrusComicCompanion.Data.PageRecord", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("ChapterId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("FileHash")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("MimeType")
                        .HasColumnType("TEXT");

                    b.Property<int>("PageNumber")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("ChapterId");

                    b.ToTable("Pages", (string)null);
                });

            modelBuilder.Entity("HydrusComicCompanion.Data.SeriesRecord", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("CoverFileHash")
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset?>("LastSyncedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Series", (string)null);
                });

            modelBuilder.Entity("HydrusComicCompanion.Data.ChapterRecord", b =>
                {
                    b.HasOne("HydrusComicCompanion.Data.SeriesRecord", "Series")
                        .WithMany("Chapters")
                        .HasForeignKey("SeriesId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Series");
                });

            modelBuilder.Entity("HydrusComicCompanion.Data.MetadataRecord", b =>
                {
                    b.HasOne("HydrusComicCompanion.Data.SeriesRecord", "Series")
                        .WithMany("Metadata")
                        .HasForeignKey("SeriesId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Series");
                });

            modelBuilder.Entity("HydrusComicCompanion.Data.PageRecord", b =>
                {
                    b.HasOne("HydrusComicCompanion.Data.ChapterRecord", "Chapter")
                        .WithMany("Pages")
                        .HasForeignKey("ChapterId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Chapter");
                });

            modelBuilder.Entity("HydrusComicCompanion.Data.ChapterRecord", b =>
                {
                    b.Navigation("Pages");
                });

            modelBuilder.Entity("HydrusComicCompanion.Data.SeriesRecord", b =>
                {
                    b.Navigation("Chapters");

                    b.Navigation("Metadata");
                });
#pragma warning restore 612, 618
        }
    }
}
