// <auto-generated />
using HydrusComicCompanion.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace HydrusComicCompanion.Data.Migrations
{
    [DbContext(typeof(SettingsDbContext))]
    partial class SettingsDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.9");

            modelBuilder.Entity("HydrusComicCompanion.Data.HydrusSettingsRecord", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("ApiUrl")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("BackgroundSyncIntervalMinutes")
                        .HasColumnType("INTEGER");

                    b.Property<string>("ChapterNamespace")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("PageNamespace")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("PrimaryTagService")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("ProtectedApiAccessKey")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("SeriesNamespace")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("TargetFileDomain")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("VolumeNamespace")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("HydrusSettings", (string)null);
                });
#pragma warning restore 612, 618
        }
    }
}
